# Generated by Django 3.1.2 on 2020-10-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('bookName', models.CharField(max_length=300)),
                ('subject', models.CharField(choices=[('M', 'Maths'), ('P', 'Physics'), ('C', 'Chemistry'), ('CS', 'Computer Science'), ('B', 'Biology'), ('E', 'English'), ('A', 'Accountancy'), ('EC', 'Economics'), ('BS', 'Business Studies'), ('EN', 'Entrepreneurship'), ('H', 'History'), ('SO', 'Sociology'), ('PS', 'Psychology')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Give',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completedFlag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completedFlag', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBTApp.ouruser')),
            ],
        ),
        migrations.CreateModel(
            name='TakeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('completedFlag', models.IntegerField(default=0)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBTApp.book')),
                ('takeNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBTApp.take')),
            ],
        ),
        migrations.CreateModel(
            name='GiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('yearPub', models.CharField(max_length=4)),
                ('condition', models.CharField(choices=[('1', 'Like new'), ('2', 'Fair'), ('3', 'Pages torn'), ('4', 'Pages missing'), ('5', 'Notes written')], max_length=1)),
                ('completedFlag', models.IntegerField(default=0)),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBTApp.book')),
                ('giveNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBTApp.give')),
            ],
        ),
        migrations.AddField(
            model_name='give',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBTApp.ouruser'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBTApp.ouruser')),
            ],
        ),
    ]
