# Generated by Django 3.1.2 on 2020-11-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBTApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveorder',
            name='yearPub',
            field=models.CharField(max_length=10),
        ),
    ]
