# Generated by Django 3.1.2 on 2020-11-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBTApp', '0003_auto_20201117_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveorder',
            name='condition',
            field=models.IntegerField(choices=[('1', 'Like new'), ('2', 'Fair'), ('3', 'Pages torn'), ('4', 'Pages missing'), ('5', 'Notes written')], max_length=1),
        ),
    ]
