# Generated by Django 3.1.2 on 2020-11-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBTApp', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
