# Generated by Django 3.1.2 on 2020-11-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBTApp', '0008_auto_20201126_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNo',
            field=models.CharField(max_length=10),
        ),
    ]
