# Generated by Django 3.1.2 on 2020-11-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBTApp', '0014_allsubjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveorder',
            name='condition',
            field=models.IntegerField(choices=[('1', 'Like new'), ('2', 'Fair'), ('3', 'Pages torn'), ('4', 'Pages missing'), ('5', 'Notes written')]),
        ),
    ]
