# Generated by Django 3.1.2 on 2020-12-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBTApp', '0017_auto_20201201_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='give',
            old_name='completedFlag',
            new_name='AckFlag',
        ),
        migrations.RenameField(
            model_name='take',
            old_name='completedFlag',
            new_name='AckFlag',
        ),
    ]
